ClassAndModuleChildren:
  Exclude:
  - 'test/**/*.rb'
Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
Naming/AccessorMethodName:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/ParameterLists:
  CountKeywordArgs: false